import type { BuiltinProviderConfig } from '../../store/types'

export const kimiConfig: BuiltinProviderConfig = {
  id: 'kimi',
  name: 'Kimi',
  type: 'builtin',
  authType: 'jwt',
  apiEndpoint: 'https://www.kimi.com',
  chatPath: '/apiv2/kimi.gateway.chat.v1.ChatService/Chat',
  headers: {
    'Content-Type': 'application/connect+json',
    'Accept': '*/*',
    'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Accept-Language': 'zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7',
    'Cache-Control': 'no-cache',
    'Pragma': 'no-cache',
    'Origin': 'https://www.kimi.com',
    'Sec-Ch-Ua': '"Google Chrome";v="131", "Chromium";v="131", "Not_A Brand";v="24"',
    'Sec-Ch-Ua-Mobile': '?0',
    'Sec-Ch-Ua-Platform': '"Windows"',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-origin',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/131.0.0.0 Safari/537.36',
    'Priority': 'u=1, i',
  },
  enabled: true,
  description: 'Kimi K2.6 AI assistant by Moonshot, supports thinking mode and web search',
  supportedModels: [
    'Kimi-K2.6',
    'Kimi-K2.6-search',
    'Kimi-K2.6-think',
    'Kimi-K2.6-search-think',
  ],
  modelMappings: {
    'Kimi-K2.6': 'kimi-k2.6',
    'Kimi-K2.6-search': 'kimi-k2.6',
    'Kimi-K2.6-think': 'kimi-k2.6',
    'Kimi-K2.6-search-think': 'kimi-k2.6',
  },
  credentialFields: [
    {
      name: 'token',
      label: '访问令牌',
      type: 'password',
      required: true,
      placeholder: '请输入 Kimi kimi-auth 或 JWT 访问令牌',
      helpText: '推荐填写浏览器 Cookie 中的 kimi-auth 字段值；JWT access token 也可使用。当前不会使用 refresh_token 做自动刷新。',
    },
    {
      name: 'cookies',
      label: '完整 Cookie（可选）',
      type: 'textarea',
      required: false,
      placeholder: '可选：从浏览器 DevTools 复制完整 Cookie 字符串',
      helpText: '用于更接近 Kimi Web 端会话形态；不填写时会自动使用 kimi-auth=<上方令牌>',
    },
    {
      name: 'deviceId',
      label: 'X-Msh-Device-Id（可选）',
      type: 'text',
      required: false,
      placeholder: '可选：Kimi Web 请求头中的 X-Msh-Device-Id',
      helpText: '可从 Kimi Web 的网络请求头复制；不填写时会从 JWT 或账号信息派生',
    },
    {
      name: 'sessionId',
      label: 'X-Msh-Session-Id（可选）',
      type: 'text',
      required: false,
      placeholder: '可选：Kimi Web 请求头中的 X-Msh-Session-Id',
      helpText: '可从 Kimi Web 的网络请求头复制；不填写时会从 JWT 或账号信息派生',
    },
  ],
  tokenCheckEndpoint: '/api/auth/token/refresh',
  tokenCheckMethod: 'GET',
}

export default kimiConfig
