import { existsSync, mkdirSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import type { RpaEndpointFinding, RpaLearningResult, RpaPatchPreview } from '../../shared/rpa'

const GENERATED_ROOT = 'src/main/rpa/generated'

export class AdapterCodeGenerator {
  generate(result: RpaLearningResult): RpaPatchPreview {
    const chat = result.primaryChat
    const confidence = chat?.confidence || 0
    const slug = createSlug(result.credentialsReference?.providerId || result.target.title || result.origin || 'learned-provider')
    const className = toPascalCase(slug)
    const models = getModels(result, chat)
    const canApply = Boolean(chat && confidence >= 60)
    const warnings = [...result.warnings]
    const outputDir = `${GENERATED_ROOT}/${slug}`

    if (!canApply) {
      warnings.push('Patch generation is read-only because the learned chat endpoint confidence is below 60.')
    }
    warnings.push('Generated artifacts are written to the RPA review folder only. Existing provider source files are never overwritten automatically.')

    const files = chat
      ? [
          {
            path: `${outputDir}/${slug}.provider.ts`,
            action: 'create' as const,
            content: createProviderConfig({ slug, result, chat, models }),
          },
          {
            path: `${outputDir}/${slug}.adapter.ts`,
            action: 'create' as const,
            content: createAdapter({ slug, className, result, chat }),
          },
          {
            path: `${outputDir}/${slug}.stream.ts`,
            action: 'create' as const,
            content: createStreamHandler({ className }),
          },
          {
            path: `${outputDir}/learning-summary.json`,
            action: 'create' as const,
            content: `${JSON.stringify(toSummary(result), null, 2)}\n`,
          },
          {
            path: `${outputDir}/registration.md`,
            action: 'create' as const,
            content: createRegistrationNotes(slug, className),
          },
        ]
      : []

    return {
      sessionId: result.sessionId,
      canApply,
      confidence,
      summary: chat
        ? `Generated ${files.length} source artifact(s) for ${slug} from ${chat.method} ${chat.path}.`
        : 'No chat endpoint was detected, so no source artifacts were generated.',
      files,
      warnings,
    }
  }

  apply(preview: RpaPatchPreview, projectRoot: string): void {
    if (!preview.canApply) {
      throw new Error('Patch cannot be applied because confidence is too low')
    }

    if (!existsSync(join(projectRoot, 'package.json')) || !existsSync(join(projectRoot, 'src'))) {
      throw new Error('Patch apply is only supported from the project source checkout')
    }

    for (const file of preview.files) {
      if (!isGeneratedReviewPath(file.path)) {
        throw new Error(`Refusing to write outside the RPA generated review folder: ${file.path}`)
      }

      const absolutePath = join(projectRoot, file.path)
      if (file.action === 'create' && existsSync(absolutePath) && !isGeneratedReviewPath(file.path)) {
        throw new Error(`Refusing to overwrite an existing source file: ${file.path}`)
      }

      mkdirSync(dirname(absolutePath), { recursive: true })
      writeFileSync(absolutePath, file.content, 'utf-8')
    }
  }
}

function isGeneratedReviewPath(path: string): boolean {
  const normalized = path.replace(/\\/g, '/')
  return normalized.startsWith(`${GENERATED_ROOT}/`) && !normalized.includes('/../')
}

function createProviderConfig(options: {
  slug: string
  result: RpaLearningResult
  chat: RpaEndpointFinding
  models: string[]
}): string {
  const authType = options.chat.authHeaders.some((header) => /cookie/i.test(header)) ? 'cookie' : 'token'
  const credentialName = authType === 'cookie' ? 'cookie' : 'token'
  const apiEndpoint = safeOrigin(options.result.origin, options.chat.url)
  const modelMappings = Object.fromEntries(options.models.map((model) => [model, model]))

  return `import type { BuiltinProviderConfig } from '../../store/types'

export const ${toCamelCase(options.slug)}Config: BuiltinProviderConfig = {
  id: '${options.slug}',
  name: '${escapeString(toTitle(options.slug))}',
  type: 'builtin',
  authType: '${authType}',
  apiEndpoint: '${escapeString(apiEndpoint)}',
  chatPath: '${escapeString(options.chat.path)}',
  headers: {
    'Content-Type': 'application/json',
    Accept: '*/*',
    Origin: '${escapeString(apiEndpoint)}',
    Referer: '${escapeString(apiEndpoint)}/',
  },
  enabled: true,
  description: 'Generated by Chat2API RPA interface learning. Review before production use.',
  supportedModels: ${JSON.stringify(options.models, null, 2)},
  modelMappings: ${JSON.stringify(modelMappings, null, 2)},
  credentialFields: [
    {
      name: '${credentialName}',
      label: '${credentialName === 'cookie' ? 'Cookie' : 'Token'}',
      type: '${credentialName === 'cookie' ? 'textarea' : 'password'}',
      required: true,
      placeholder: 'Enter ${credentialName === 'cookie' ? 'Cookie' : 'Token'}',
      helpText: 'Captured field names: ${escapeString(options.chat.authHeaders.join(', ') || 'none')}',
    },
  ],
}

export default ${toCamelCase(options.slug)}Config
`
}

function createAdapter(options: {
  slug: string
  className: string
  result: RpaLearningResult
  chat: RpaEndpointFinding
}): string {
  const template = findRequestTemplate(options.result, options.chat)

  return `import axios, { AxiosResponse } from 'axios'
import type { Account, Provider } from '../../store/types'
import type { ChatCompletionRequest } from '../types'
import { applyAxiosProxyConfig, type OutboundProxyContext } from '../proxyTransport'

const LEARNED_REQUEST_TEMPLATE = ${JSON.stringify(template, null, 2)}

export class ${options.className}Adapter {
  constructor(
    private readonly provider: Provider,
    private readonly account: Account,
    private readonly outboundProxy?: OutboundProxyContext,
  ) {}

  async chatCompletion(request: ChatCompletionRequest): Promise<{ response: AxiosResponse; sessionId: string }> {
    const url = new URL(this.provider.chatPath || '${escapeString(options.chat.path)}', this.provider.apiEndpoint).toString()
    const headers = this.buildHeaders()
    const payload = buildRequestPayload(LEARNED_REQUEST_TEMPLATE, request)
    const response = await axios.request(applyAxiosProxyConfig({
      method: '${options.chat.method}',
      url,
      headers,
      data: payload,
      responseType: request.stream ? 'stream' : 'json',
      timeout: 120000,
      validateStatus: () => true,
    }, this.outboundProxy))

    return {
      response,
      sessionId: \`rpa-\${Date.now()}\`,
    }
  }

  async deleteSession(): Promise<boolean> {
    return true
  }

  static is${options.className}Provider(provider: Provider): boolean {
    return provider.id === '${options.slug}'
  }

  private buildHeaders(): Record<string, string> {
    const headers: Record<string, string> = {
      ...this.provider.headers,
    }

    const credentials = this.account.credentials || {}
    if (credentials.token) {
      headers.Authorization = \`Bearer \${credentials.token}\`
    }
    if (credentials.apiKey) {
      headers.Authorization = \`Bearer \${credentials.apiKey}\`
    }
    if (credentials.cookie) {
      headers.Cookie = credentials.cookie
    }

    return headers
  }
}

function buildRequestPayload(template: unknown, request: ChatCompletionRequest): Record<string, unknown> {
  const payload = cloneTemplate(template)
  const lastUserText = getLastUserText(request)

  if (Array.isArray(payload.messages) || 'messages' in payload) {
    payload.messages = request.messages
  }
  if ('model' in payload || !Object.keys(payload).length) {
    payload.model = request.model
  }
  if ('stream' in payload) {
    payload.stream = Boolean(request.stream)
  }
  for (const key of ['prompt', 'query', 'input', 'text', 'content']) {
    if (key in payload && typeof payload[key] === 'string') {
      payload[key] = lastUserText
    }
  }

  if (!('messages' in payload) && !('prompt' in payload) && !('query' in payload) && !('input' in payload)) {
    payload.model = request.model
    payload.messages = request.messages
    payload.stream = Boolean(request.stream)
  }

  return payload
}

function cloneTemplate(template: unknown): Record<string, unknown> {
  if (!template || typeof template !== 'object' || Array.isArray(template)) {
    return {}
  }

  return JSON.parse(JSON.stringify(template)) as Record<string, unknown>
}

function getLastUserText(request: ChatCompletionRequest): string {
  const lastUser = [...request.messages].reverse().find((message) => message.role === 'user')
  if (!lastUser) return ''
  if (typeof lastUser.content === 'string') return lastUser.content
  if (!Array.isArray(lastUser.content)) return ''
  return lastUser.content
    .filter((part) => part.type === 'text' && part.text)
    .map((part) => part.text)
    .join('\\n')
}

export const ${toCamelCase(options.slug)}Adapter = { ${options.className}Adapter }
`
}

function createStreamHandler(options: { className: string }): string {
  return `import { PassThrough } from 'stream'

export class ${options.className}StreamHandler {
  private readonly created = Math.floor(Date.now() / 1000)

  constructor(
    private readonly model: string,
    private readonly sessionId: string,
  ) {}

  async handleStream(stream: NodeJS.ReadableStream): Promise<NodeJS.ReadableStream> {
    const transformed = new PassThrough()

    stream.on('data', (chunk: Buffer) => {
      const text = chunk.toString('utf-8')
      for (const line of text.split('\\n')) {
        const trimmed = line.trim()
        if (!trimmed || trimmed === 'data: [DONE]') continue
        const jsonText = trimmed.startsWith('data:') ? trimmed.slice(5).trim() : trimmed
        const content = extractContent(jsonText)
        if (content) {
          transformed.write(this.createChunk({ content }))
        }
      }
    })

    stream.on('end', () => {
      transformed.write(this.createChunk({}, 'stop'))
      transformed.write('data: [DONE]\\n\\n')
      transformed.end()
    })

    stream.on('error', (error) => transformed.destroy(error))
    return transformed
  }

  async handleNonStream(input: NodeJS.ReadableStream | unknown): Promise<Record<string, unknown>> {
    const body = typeof input === 'object' && input && 'pipe' in input
      ? await collectStream(input as NodeJS.ReadableStream)
      : JSON.stringify(input || {})
    const content = extractContent(body) || body

    return {
      id: this.sessionId,
      object: 'chat.completion',
      created: this.created,
      model: this.model,
      choices: [
        {
          index: 0,
          message: {
            role: 'assistant',
            content,
          },
          finish_reason: 'stop',
        },
      ],
    }
  }

  private createChunk(delta: Record<string, unknown>, finishReason?: string): string {
    return \`data: \${JSON.stringify({
      id: this.sessionId,
      object: 'chat.completion.chunk',
      created: this.created,
      model: this.model,
      choices: [{ index: 0, delta, finish_reason: finishReason || null }],
    })}\\n\\n\`
  }
}

async function collectStream(stream: NodeJS.ReadableStream): Promise<string> {
  const chunks: Buffer[] = []
  for await (const chunk of stream) {
    chunks.push(Buffer.isBuffer(chunk) ? chunk : Buffer.from(String(chunk)))
  }
  return Buffer.concat(chunks).toString('utf-8')
}

function extractContent(value: string): string {
  try {
    const parsed = JSON.parse(value)
    return findString(parsed, ['content', 'text', 'answer', 'delta', 'message']) || ''
  } catch {
    return ''
  }
}

function findString(value: unknown, keys: string[], depth = 0): string | undefined {
  if (depth > 5 || !value) return undefined
  if (typeof value === 'string') return value
  if (Array.isArray(value)) {
    for (const item of value) {
      const found = findString(item, keys, depth + 1)
      if (found) return found
    }
    return undefined
  }
  if (typeof value === 'object') {
    const object = value as Record<string, unknown>
    for (const key of keys) {
      if (typeof object[key] === 'string') {
        return object[key] as string
      }
    }
    for (const nested of Object.values(object)) {
      const found = findString(nested, keys, depth + 1)
      if (found) return found
    }
  }
  return undefined
}
`
}

function createRegistrationNotes(slug: string, className: string): string {
  return `# RPA Registration Notes: ${slug}

The generated source artifacts compile as reviewable templates. To make this provider active in Chat2API, review the learned protocol and then wire these generated classes into:

- \`src/main/providers/builtin/index.ts\`
- \`src/main/store/types.ts\` \`BUILTIN_PROVIDERS\`
- \`src/main/proxy/adapters/index.ts\`
- \`src/main/proxy/forwarder.ts\` provider forwarder list
- renderer i18n/provider icon mapping, if this should be visible as a built-in provider

Suggested adapter classes:

- \`${className}Adapter\`
- \`${className}StreamHandler\`

Keep this file with the learning summary until the generated provider has been manually reviewed.
`
}

function findRequestTemplate(result: RpaLearningResult, chat: RpaEndpointFinding): unknown {
  const source = result.requests.find((request) => request.url === chat.url && request.method === chat.method)
  if (!source?.requestBody) return {}

  try {
    return JSON.parse(source.requestBody)
  } catch {
    return {}
  }
}

function toSummary(result: RpaLearningResult): Record<string, unknown> {
  return {
    sessionId: result.sessionId,
    target: result.target,
    origin: result.origin,
    capturedAt: result.capturedAt,
    primaryChat: result.primaryChat,
    findings: result.findings,
    warnings: result.warnings,
    credentialsReference: result.credentialsReference,
  }
}

function getModels(result: RpaLearningResult, chat: RpaEndpointFinding | undefined): string[] {
  const learned = result.findings.flatMap((finding) => finding.models || [])
  if (learned.length > 0) {
    return Array.from(new Set(learned)).slice(0, 30)
  }

  const source = chat ? result.requests.find((request) => request.url === chat.url) : undefined
  const requestModel = source?.requestBody?.match(/"model"\s*:\s*"([^"]+)"/)?.[1]
  return requestModel ? [requestModel] : ['learned-model']
}

function createSlug(value: string): string {
  const slug = value
    .toLowerCase()
    .replace(/^https?:\/\//, '')
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '')
    .slice(0, 48)

  const normalized = slug || `learned-${Date.now()}`
  return /^[a-z]/.test(normalized) ? normalized : `learned-${normalized}`
}

function toPascalCase(value: string): string {
  return value
    .split('-')
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join('')
}

function toCamelCase(value: string): string {
  const pascal = toPascalCase(value)
  return `${pascal.charAt(0).toLowerCase()}${pascal.slice(1)}`
}

function toTitle(value: string): string {
  return value
    .split('-')
    .filter(Boolean)
    .map((part) => `${part.charAt(0).toUpperCase()}${part.slice(1)}`)
    .join(' ')
}

function safeOrigin(origin: string, fallbackUrl: string): string {
  if (origin) return origin
  try {
    return new URL(fallbackUrl).origin
  } catch {
    return 'https://example.com'
  }
}

function escapeString(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/'/g, "\\'")
}
